
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";
import { Web3Provider } from './providers/web3Provider'
import { Head } from "next/document";
import { ApolloProvider } from '@apollo/client';
import client from '../lib/apolloClient';
import ApolloWrapper from "@/lib/ApolloWrapper";


const inter = Inter({ subsets: ["latin"] });

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body  className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        ) } > 
          {/* <ApolloWrapper> */}
          <Web3Provider>
            {children}
          </Web3Provider>
        {/* </ApolloWrapper> */}
      </body>
    </html>
  );
}
